# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test with py.test

on:
  pull_request:
  merge_group:
  workflow_call:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
    - name: Install system dependencies for Chromium
      run: sudo apt-get update && sudo apt-get install -y chromium-browser

    - name: Set up Pyppeteer to use system Chromium
      run: |
          mkdir -p ~/.local/share/pyppeteer/local-chromium
          ln -s /usr/bin/chromium-browser ~/.local/share/pyppeteer/local-chromium/1181205

    - name: Run tests
      env:
        PYPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium-browser"  # ✅ Force Pyppeteer to use system Chromium
      run: pytest tests/