name: Test with py.test

on:
  pull_request:
  merge_group:
  workflow_call:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"

    # ✅ Explicitly install dependencies
    - name: Install Python dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install pytest
      shell: bash

    # ✅ Install Chromium based on OS
    - name: Install Chromium (Ubuntu)
      if: runner.os == 'Linux'
      run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser || sudo apt-get install -y chromium

    - name: Install Chromium (macOS)
      if: runner.os == 'macOS'
      run: |
          brew install chromium
          echo "PYPPETEER_EXECUTABLE_PATH=$(which chromium)" >> $GITHUB_ENV
      shell: bash

    - name: Install Chromium (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        choco install chromium -y
        $chromePath = (Get-Command chrome -ErrorAction SilentlyContinue).Source
        if ($chromePath) {
            echo "PYPPETEER_EXECUTABLE_PATH=$chromePath" >> $env:GITHUB_ENV
        } else {
            echo "Chromium installation failed or not found!" 
            exit 1
        }
      

    # ✅ Remove Pyppeteer's auto-downloaded Chromium (forces use of system Chromium)
    - name: Remove Pyppeteer Chromium Cache
      run: rm -rf ~/Library/Application\ Support/pyppeteer/local-chromium
      if: runner.os == 'macOS'
      shell: bash

    # ✅ Ensure Pyppeteer uses the correct Chromium path
    - name: Set up Pyppeteer
      if: runner.os != 'Linux'
      run: |
          mkdir -p ~/.local/share/pyppeteer/local-chromium
          ln -sf $(which chromium-browser || which chromium || which chromium.app/Contents/MacOS/Chromium) ~/.local/share/pyppeteer/local-chromium/1181205
      shell: bash

    - name: Set up Pyppeteer (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        $chromePath = (Get-Command chrome -ErrorAction SilentlyContinue).Source
        if ($chromePath) {
            New-Item -ItemType Directory -Force "$HOME/.local/share/pyppeteer/local-chromium" | Out-Null
            Copy-Item $chromePath "$HOME/.local/share/pyppeteer/local-chromium/1181205"
        } else {
            echo "Chromium path not found!" 
            exit 1
        }

    # ✅ Check pytest installation
    - name: Check pytest installation
      run: python -m pytest --version

    # ✅ Run tests
    - name: Run tests
      env:
        PYPPETEER_EXECUTABLE_PATH: ${{ env.PYPPETEER_EXECUTABLE_PATH || '/usr/bin/chromium-browser' }}
      run: python -m pytest tests/
