name: Test with py.test

on:
  pull_request:
  merge_group:
  workflow_call:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"

    # ✅ Explicitly install dependencies before running tests
    - name: Install Python dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install pytest  # ✅ Ensures pytest is installed
      shell: bash

    # ✅ Install Chromium based on OS
    - name: Install Chromium (Ubuntu)
      if: runner.os == 'Linux'
      run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser || sudo apt-get install -y chromium

    - name: Install Chromium (macOS)
      if: runner.os == 'macOS'
      run: brew install chromium

    - name: Install Chromium (Windows)
      if: runner.os == 'Windows'
      run: |
          choco install chromium
          echo "PYPPETEER_EXECUTABLE_PATH=C:\Program Files\Chromium\Application\chrome.exe" >> $GITHUB_ENV

    # ✅ Set up Pyppeteer to use system Chromium
    - name: Set up Pyppeteer
      run: |
          mkdir -p ~/.local/share/pyppeteer/local-chromium
          ln -sf $(which chromium-browser || which chromium || which chromium.app/Contents/MacOS/Chromium || echo "C:\Program Files\Chromium\Application\chrome.exe") ~/.local/share/pyppeteer/local-chromium/1181205
      shell: bash

    # ✅ Ensure pytest is available before running tests
    - name: Check pytest installation
      run: python -m pytest --version

    # ✅ Run tests
    - name: Run tests
      env:
        PYPPETEER_EXECUTABLE_PATH: ${{ env.PYPPETEER_EXECUTABLE_PATH || '/usr/bin/chromium-browser' }}
      run: python -m pytest tests/
